// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package courier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageServerClient is the client API for MessageServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServerClient interface {
	PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error)
	RequestMessage(ctx context.Context, in *RequestMessageRequest, opts ...grpc.CallOption) (*RequestMessageResponse, error)
	ResponseMessage(ctx context.Context, in *ResponseMessageRequest, opts ...grpc.CallOption) (*ResponseMessageResponse, error)
}

type messageServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServerClient(cc grpc.ClientConnInterface) MessageServerClient {
	return &messageServerClient{cc}
}

func (c *messageServerClient) PublishMessage(ctx context.Context, in *PublishMessageRequest, opts ...grpc.CallOption) (*PublishMessageResponse, error) {
	out := new(PublishMessageResponse)
	err := c.cc.Invoke(ctx, "/messenger.MessageServer/PublishMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServerClient) RequestMessage(ctx context.Context, in *RequestMessageRequest, opts ...grpc.CallOption) (*RequestMessageResponse, error) {
	out := new(RequestMessageResponse)
	err := c.cc.Invoke(ctx, "/messenger.MessageServer/RequestMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServerClient) ResponseMessage(ctx context.Context, in *ResponseMessageRequest, opts ...grpc.CallOption) (*ResponseMessageResponse, error) {
	out := new(ResponseMessageResponse)
	err := c.cc.Invoke(ctx, "/messenger.MessageServer/ResponseMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServerServer is the server API for MessageServer service.
// All implementations must embed UnimplementedMessageServerServer
// for forward compatibility
type MessageServerServer interface {
	PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error)
	RequestMessage(context.Context, *RequestMessageRequest) (*RequestMessageResponse, error)
	ResponseMessage(context.Context, *ResponseMessageRequest) (*ResponseMessageResponse, error)
	mustEmbedUnimplementedMessageServerServer()
}

// UnimplementedMessageServerServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServerServer struct {
}

func (UnimplementedMessageServerServer) PublishMessage(context.Context, *PublishMessageRequest) (*PublishMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedMessageServerServer) RequestMessage(context.Context, *RequestMessageRequest) (*RequestMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestMessage not implemented")
}
func (UnimplementedMessageServerServer) ResponseMessage(context.Context, *ResponseMessageRequest) (*ResponseMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResponseMessage not implemented")
}
func (UnimplementedMessageServerServer) mustEmbedUnimplementedMessageServerServer() {}

// UnsafeMessageServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServerServer will
// result in compilation errors.
type UnsafeMessageServerServer interface {
	mustEmbedUnimplementedMessageServerServer()
}

func RegisterMessageServerServer(s grpc.ServiceRegistrar, srv MessageServerServer) {
	s.RegisterService(&MessageServer_ServiceDesc, srv)
}

func _MessageServer_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServerServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messenger.MessageServer/PublishMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServerServer).PublishMessage(ctx, req.(*PublishMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageServer_RequestMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServerServer).RequestMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messenger.MessageServer/RequestMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServerServer).RequestMessage(ctx, req.(*RequestMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageServer_ResponseMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResponseMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServerServer).ResponseMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messenger.MessageServer/ResponseMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServerServer).ResponseMessage(ctx, req.(*ResponseMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageServer_ServiceDesc is the grpc.ServiceDesc for MessageServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messenger.MessageServer",
	HandlerType: (*MessageServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishMessage",
			Handler:    _MessageServer_PublishMessage_Handler,
		},
		{
			MethodName: "RequestMessage",
			Handler:    _MessageServer_RequestMessage_Handler,
		},
		{
			MethodName: "ResponseMessage",
			Handler:    _MessageServer_ResponseMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
