// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	courier "github.com/platform-edn/courier/pkg/courier"
	mock "github.com/stretchr/testify/mock"
)

// CourierServiceOption is an autogenerated mock type for the CourierServiceOption type
type CourierServiceOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CourierServiceOption) Execute(_a0 *courier.CourierService) {
	_m.Called(_a0)
}
