// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	messaging "github.com/platform-edn/courier/pkg/messaging"
	mock "github.com/stretchr/testify/mock"
)

// MessageReceiver is an autogenerated mock type for the MessageReceiver type
type MessageReceiver struct {
	mock.Mock
}

// ResponseChannel provides a mock function with given fields:
func (_m *MessageReceiver) ResponseChannel() <-chan messaging.ResponseInfo {
	ret := _m.Called()

	var r0 <-chan messaging.ResponseInfo
	if rf, ok := ret.Get(0).(func() <-chan messaging.ResponseInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan messaging.ResponseInfo)
		}
	}

	return r0
}

// SubscribeToSubject provides a mock function with given fields: _a0
func (_m *MessageReceiver) SubscribeToSubject(_a0 string) <-chan messaging.Message {
	ret := _m.Called(_a0)

	var r0 <-chan messaging.Message
	if rf, ok := ret.Get(0).(func(string) <-chan messaging.Message); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan messaging.Message)
		}
	}

	return r0
}
