// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	registry "github.com/platform-edn/courier/pkg/registry"

	sync "sync"
)

// NodeEventer is an autogenerated mock type for the NodeEventer type
type NodeEventer struct {
	mock.Mock
}

// DiscoverNodeEvents provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *NodeEventer) DiscoverNodeEvents(_a0 context.Context, _a1 chan registry.NodeEvent, _a2 chan error, _a3 *sync.WaitGroup) {
	_m.Called(_a0, _a1, _a2, _a3)
}
