// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package messenger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageServerClient is the client API for MessageServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServerClient interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
}

type messageServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServerClient(cc grpc.ClientConnInterface) MessageServerClient {
	return &messageServerClient{cc}
}

func (c *messageServerClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, "/messenger.MessageServer/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServerServer is the server API for MessageServer service.
// All implementations must embed UnimplementedMessageServerServer
// for forward compatibility
type MessageServerServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	mustEmbedUnimplementedMessageServerServer()
}

// UnimplementedMessageServerServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServerServer struct {
}

func (UnimplementedMessageServerServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageServerServer) mustEmbedUnimplementedMessageServerServer() {}

// UnsafeMessageServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServerServer will
// result in compilation errors.
type UnsafeMessageServerServer interface {
	mustEmbedUnimplementedMessageServerServer()
}

func RegisterMessageServerServer(s grpc.ServiceRegistrar, srv MessageServerServer) {
	s.RegisterService(&MessageServer_ServiceDesc, srv)
}

func _MessageServer_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServerServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messenger.MessageServer/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServerServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageServer_ServiceDesc is the grpc.ServiceDesc for MessageServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messenger.MessageServer",
	HandlerType: (*MessageServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _MessageServer_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
