// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Locker is an autogenerated mock type for the Locker type
type Locker struct {
	mock.Mock
}

// Lock provides a mock function with given fields:
func (_m *Locker) Lock() {
	_m.Called()
}

// Unlock provides a mock function with given fields:
func (_m *Locker) Unlock() {
	_m.Called()
}
