// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	node "github.com/platform-edn/courier/node"
	mock "github.com/stretchr/testify/mock"
)

// NodeMapper is an autogenerated mock type for the NodeMapper type
type NodeMapper struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *NodeMapper) Add(_a0 node.Node) {
	_m.Called(_a0)
}

// Length provides a mock function with given fields:
func (_m *NodeMapper) Length() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Node provides a mock function with given fields: _a0
func (_m *NodeMapper) Node(_a0 string) (node.Node, bool) {
	ret := _m.Called(_a0)

	var r0 node.Node
	if rf, ok := ret.Get(0).(func(string) node.Node); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(node.Node)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: _a0
func (_m *NodeMapper) Remove(_a0 string) {
	_m.Called(_a0)
}

// Update provides a mock function with given fields: _a0
func (_m *NodeMapper) Update(_a0 ...node.Node) {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
