// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	registry "github.com/platform-edn/courier/pkg/registry"
	mock "github.com/stretchr/testify/mock"
)

// SubscriberLister is an autogenerated mock type for the SubscriberLister type
type SubscriberLister struct {
	mock.Mock
}

// CloseListeners provides a mock function with given fields:
func (_m *SubscriberLister) CloseListeners() {
	_m.Called()
}

// ForwardEvent provides a mock function with given fields: event
func (_m *SubscriberLister) ForwardEvent(event registry.NodeEvent) {
	_m.Called(event)
}

// SubscribeToEvents provides a mock function with given fields:
func (_m *SubscriberLister) SubscribeToEvents() chan registry.NodeEvent {
	ret := _m.Called()

	var r0 chan registry.NodeEvent
	if rf, ok := ret.Get(0).(func() chan registry.NodeEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan registry.NodeEvent)
		}
	}

	return r0
}
