// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EventStreamer is an autogenerated mock type for the EventStreamer type
type EventStreamer struct {
	mock.Mock
}

// StreamEvents provides a mock function with given fields: ctx, subscribed, broadcasted
func (_m *EventStreamer) StreamEvents(ctx context.Context, subscribed []string, broadcasted []string) error {
	ret := _m.Called(ctx, subscribed, broadcasted)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) error); ok {
		r0 = rf(ctx, subscribed, broadcasted)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
