// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	eventer "github.com/platform-edn/courier/pkg/eventer"
	mock "github.com/stretchr/testify/mock"
)

// OperatorClientOption is an autogenerated mock type for the OperatorClientOption type
type OperatorClientOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: client
func (_m *OperatorClientOption) Execute(client *eventer.OperatorClient) {
	_m.Called(client)
}
