// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	proto "github.com/platform-edn/courier/pkg/proto"
	mock "github.com/stretchr/testify/mock"
)

// DiscoverServer is an autogenerated mock type for the DiscoverServer type
type DiscoverServer struct {
	mock.Mock
}

// SubscribeToNodeEvents provides a mock function with given fields: _a0, _a1
func (_m *DiscoverServer) SubscribeToNodeEvents(_a0 *proto.EventStreamRequest, _a1 proto.Discover_SubscribeToNodeEventsServer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*proto.EventStreamRequest, proto.Discover_SubscribeToNodeEventsServer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mustEmbedUnimplementedDiscoverServer provides a mock function with given fields:
func (_m *DiscoverServer) mustEmbedUnimplementedDiscoverServer() {
	_m.Called()
}
