// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/platform-edn/courier/pkg/proto"
)

// MessageClient is an autogenerated mock type for the MessageClient type
type MessageClient struct {
	mock.Mock
}

// PublishMessage provides a mock function with given fields: ctx, in, opts
func (_m *MessageClient) PublishMessage(ctx context.Context, in *proto.PublishMessageRequest, opts ...grpc.CallOption) (*proto.PublishMessageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.PublishMessageResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.PublishMessageRequest, ...grpc.CallOption) *proto.PublishMessageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.PublishMessageResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.PublishMessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestMessage provides a mock function with given fields: ctx, in, opts
func (_m *MessageClient) RequestMessage(ctx context.Context, in *proto.RequestMessageRequest, opts ...grpc.CallOption) (*proto.RequestMessageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.RequestMessageResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RequestMessageRequest, ...grpc.CallOption) *proto.RequestMessageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RequestMessageResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.RequestMessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResponseMessage provides a mock function with given fields: ctx, in, opts
func (_m *MessageClient) ResponseMessage(ctx context.Context, in *proto.ResponseMessageRequest, opts ...grpc.CallOption) (*proto.ResponseMessageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.ResponseMessageResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ResponseMessageRequest, ...grpc.CallOption) *proto.ResponseMessageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ResponseMessageResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.ResponseMessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
