// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeMessageServer is an autogenerated mock type for the UnsafeMessageServer type
type UnsafeMessageServer struct {
	mock.Mock
}

// mustEmbedUnimplementedMessageServer provides a mock function with given fields:
func (_m *UnsafeMessageServer) mustEmbedUnimplementedMessageServer() {
	_m.Called()
}
