// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeDiscoverServer is an autogenerated mock type for the UnsafeDiscoverServer type
type UnsafeDiscoverServer struct {
	mock.Mock
}

// mustEmbedUnimplementedDiscoverServer provides a mock function with given fields:
func (_m *UnsafeDiscoverServer) mustEmbedUnimplementedDiscoverServer() {
	_m.Called()
}
