name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  buildPush:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17' 

      - name: Install Mockery
        run: go install github.com/vektra/mockery && echo $GOBIN

      - name: Create Mocks
        uses: magefile/mage-action@v1
        with:
          args: mock

      - name: Run Tests
        uses: magefile/mage-action@v1
        with:
          args: -v race