name: Test
on:
  pull_request:
    branches:
      - main
env:
  GOPATH: "/go"
  GOBIN: "/go/bin"
jobs:
  buildPush:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set Up Go
        uses: actions/setup-go@v2

      - name: Install Mockery
        run: go install github.com/vektra/mockery

      - name: Add GOBIN to PATH
        run: echo $GOBIN >> $GITHUB_PATH

      - name: Create Mocks
        uses: magefile/mage-action@v1
        with:
          args: mock

      - name: Run Tests
        uses: magefile/mage-action@v1
        with:
          args: -v race