name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  buildPush:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set Up Go
        uses: actions/setup-go@v2

      - name: Run Mage
        uses: magefile/mage-action@v1
        with:
          args: -v race